version: 0.0
os: linux

files:
  - source: /
    destination: bookeroo/
hooks: 
  ApplicationStop:
    - location: docker-stop.sh
  ApplicationStart:
    - location: BackEnd/loginmicroservices/build-run-docker.sh
    - location: frontend/bookeroo/run-web.sh